#!/usr/bin/env bash
#displays 'I am alive!' indefinitely
while "true"
do
	echo "I am alive!" > /tmp/my_process
	sleep 2
#manage
if [[ "$#" == "1" ]]; then
  if [[ "$1" == "start" ]]; then
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
  elif [[ "$1" == "stop" ]]; then
    if test -f "/var/run/my_process.pid"; then
      kill "$(cat /var/run/my_process.pid)"
    fi
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
  elif [[ "$1" == "restart" ]]; then
    # stop program
    if test -f "/var/run/my_process.pid"; then
      kill "$(cat /var/run/my_process.pid)"
    fi
    # start program
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
  else
    echo "Usage: manage_my_process {start|stop|restart}"
  fi
else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
